# Generated by Django 4.0.5 on 2022-06-18 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='time',
            field=models.TimeField(default='19:01:25:58'),
        ),
        migrations.AlterField(
            model_name='item',
            name='time',
            field=models.TimeField(default='19:01:25:58'),
        ),
    ]
