# Generated by Django 4.0.5 on 2022-06-18 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_history_time_alter_item_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='time',
            field=models.TimeField(default='01:29:54'),
        ),
        migrations.AlterField(
            model_name='item',
            name='time',
            field=models.TimeField(default='01:29:54'),
        ),
    ]
