# Generated by Django 4.0.5 on 2022-06-18 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_history_time_alter_item_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='time',
            field=models.TimeField(default='02:06:02'),
        ),
        migrations.AlterField(
            model_name='item',
            name='time',
            field=models.TimeField(default='02:06:02'),
        ),
    ]
